inherit_from: '.rubocop_todo.yml'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'kirico.gemspec'

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'kirico.gemspec'
